[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0.197"
serde_json = "1.0.114"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2"
hex = "0.4.3"
sp1-sdk = "2.0.0"